"""USO database layer — re-exports all CRUD operations."""

from .connection import DEFAULT_DB_PATH, _local, get_connection, init_db
from .edges import create_edge, delete_edge, get_edge, list_edges
from .runs import create_artifact, create_run, get_artifacts, get_runs, update_run
from .schedules import (
    create_schedule,
    delete_schedule,
    get_schedule,
    list_schedules,
    update_schedule_enabled,
)
from .scripts import (
    add_parameter,
    create_script,
    delete_parameter,
    delete_script,
    get_parameters,
    get_script,
    get_script_by_name,
    list_scripts,
    update_script,
)
from .tags import (
    create_tag,
    delete_tag,
    get_script_tags,
    get_scripts_by_tag,
    get_tag,
    get_tag_by_name,
    list_tags,
    tag_script,
    untag_script,
)
from .workflows import (
    add_node,
    add_workflow_edge,
    create_node_run,
    create_workflow,
    create_workflow_run,
    delete_node,
    delete_workflow,
    delete_workflow_edge,
    get_node_runs,
    get_nodes,
    get_workflow,
    get_workflow_edges,
    get_workflow_run,
    list_workflow_runs,
    list_workflows,
    update_node_run,
    update_workflow_run,
)

__all__ = [
    "DEFAULT_DB_PATH",
    "_local",
    "add_node",
    "add_parameter",
    "add_workflow_edge",
    "create_artifact",
    "create_edge",
    "create_node_run",
    "create_run",
    "create_schedule",
    "create_script",
    "create_tag",
    "create_workflow",
    "create_workflow_run",
    "delete_edge",
    "delete_node",
    "delete_parameter",
    "delete_schedule",
    "delete_script",
    "delete_tag",
    "delete_workflow",
    "delete_workflow_edge",
    "get_artifacts",
    "get_connection",
    "get_edge",
    "get_node_runs",
    "get_nodes",
    "get_parameters",
    "get_runs",
    "get_schedule",
    "get_script",
    "get_script_by_name",
    "get_script_tags",
    "get_scripts_by_tag",
    "get_tag",
    "get_tag_by_name",
    "get_workflow",
    "get_workflow_edges",
    "get_workflow_run",
    "init_db",
    "list_edges",
    "list_schedules",
    "list_scripts",
    "list_tags",
    "list_workflow_runs",
    "list_workflows",
    "tag_script",
    "untag_script",
    "update_node_run",
    "update_run",
    "update_schedule_enabled",
    "update_script",
    "update_workflow_run",
]
